theme: jekyll-theme-cayman

github:
  is_project_page: false
  
markdown: kramdown
kramdown:
  math_engine: katex

title: CSL-L2M
description: Controllable Song-Level Lyric-to-Melody Generation based on Conditional Transformer with Fine-Grained Lyric and Musical Controls
